### ISSUE TITLE
proxy to multiple endpoints in one container

### ISSUE THREAD

**Issue by codekitchen** [codekitchen/dinghy-http-proxy#16]
This isn't a super common need, since best practice is to have one process running per container, but sometimes even one process might expose more than one HTTP server: one port for public connections, another port for an internal admin UI, for example. There's no fundamental reason the proxy can't handle this, but it'll take changes to how the env vars are interpreted.

One idea is to look for vars of the form `VIRTUAL_HOST_X` and `VIRTUAL_PORT_X`, where X is any number > 1, but there might be a better option.

**Comment by hirnschmalz** [comment]
+1 for that.

In a CMS like TYPO3 for example you can have a multi domain setup. Here it would perfectly make sense to have the ability to proxy to multiple endpoints. Maybe it would be easier to handle multiple definitions by separate them by a special sign (space or ';' for example).

**Comment by codekitchen** [comment]
does TYPO3 actually listen on different ports for the different domains? Usually in a situation like that, it's just one HTTP server that responds to different domains based on the `Host:` header, which is already supported https://github.com/jwilder/nginx-proxy#multiple-hosts

Just noticed that feature isn't mentioned in this project's README, I'll update it

**Comment by hirnschmalz** [comment]
Hi @codekitchen , TYPO3 does not list on different ports (if we ignoren HTTP vs HTTPS) for different domains. It works like you described based on the **Host** header. So for 90% of the usecases the undocumented feature with the comma separated list works great. A problem will occure if one domain runs on HTTP and another in the same TYPO3 instance runs on HTTPS.

**Comment by codekitchen** [comment]
Cool, I've updated the README to include a section on that feature

**Comment by hirnschmalz** [comment]
Great! Thx

**Comment by rwstauner** [comment]
I think this would be a great feature.  It may not be "the docker way" to have more than one proc in a container, but it can be really handy for a lot of cases, especially for development (which is where dinghy is useful).  There are a lot of images that ship this way because it's pragmatic to combine services for ease of setup.

Would it be difficult (or backward incompatible) to simply expand VIRTUAL_HOST to allow for `name1:8000,name2:9000` ?

**Comment by codekitchen** [comment]
Yeah that seems like probably the best option, and yes it's backwards compatible. If somebody wants to send over a PR for it I'd be happy to pull it in.
