### ISSUE TITLE
change server_names_hash_bucket_size 64 -> 128; @ nginx.conf

### ISSUE THREAD

**Issue by kornel-kedzierski** [codekitchen/dinghy-http-proxy#2]

**Comment by vincetse** [comment]
@codekitchen:
You should probably base this off of `jwilder/nginx-proxy:0.2.0` and not `jwilder/nginx-proxy:0.3.6`.  0.3.6 [hasn't been updated in months](https://hub.docker.com/r/jwilder/nginx-proxy/tags/), and doesn't have [the setting you need](https://github.com/jwilder/nginx-proxy/commit/d7e499e4e63d9bbd39f885e2e2be6a7fb6a7671b) in the `nginx.conf` file.

**Comment by codekitchen** [comment]
Hm yeah. Actually, `0.2.0` isn't what we want either. While it's been rebuilt 8 days ago, it is still based on older code than `0.3.6`, I just verified by pulling it down. However, `latest` has the changes we're interested in, both this config change and the newer version of docker-gen that has my added function.

Seems a shame that they haven't tagged a new version besides just `latest`, but I can use that tag for now while I ask them what's up. Thanks for the pointer.

**Comment by codekitchen** [comment]
OK dinghy master has this updated base image, and i've verified this value is updated to 128. thanks again.

**Comment by vincetse** [comment]
Thanks for the quick fix!

**Comment by KamilKopaczyk** [comment]
Looks like due to [this](https://github.com/jwilder/nginx-proxy/commit/b0de80d46b63f353a198e2110aa2b03ad26e691d) change this problem got reintroduced. 
`nginx.tmpl` file gets overridden by dinghy's version and `server_names_hash_bucket_size setting` is not set at all.

**Comment by codekitchen** [comment]
Good catch thanks, I've pushed up https://github.com/codekitchen/dinghy-http-proxy/commit/d96dbee0b89eb208cbfa63735982c1b1ae470311 and I'll push a new version once I try it out

**Comment by Mpreyzner** [comment]
Can you please push a new version with the fix? I'd be super grateful.  Changing server_names_hash_bucket_size for every time I start dinghy is quite tedious.

**Comment by codekitchen** [comment]
Oh whoops, thought I already had. Just pushed version 2.5.8, you can force Dinghy to update to it immediately by running `docker pull codekitchen/dinghy-http-proxy:2.5` and then `dinghy restart`.
