### ISSUE TITLE
How to point to app?

### ISSUE THREAD

**Issue by jaesung2061** [codekitchen/dinghy-http-proxy#25]
Going to *.docker takes me to here:

![test](http://i.imgur.com/mBEJzTq.png "test")

What am I supposed to do from this point? I can't seem to find any documentation on setting up a proxy..

**Comment by codekitchen** [comment]
Did you read through that linked configuration documentation? That explains how to connect to your running containers, whether they are started via docker-compose or otherwise. There's a quick summary at https://github.com/codekitchen/dinghy#http-proxy as well

**Comment by jaesung2061** [comment]
I'm not sure what this part means..

> Hostnames can also be manually defined, by setting the `VIRTUAL_HOST` environment variable on a container

What is the container in question? And how do I find out what the value of `VIRTUAL_HOST` is?

**Comment by codekitchen** [comment]
Maybe I should copy over the `Usage` section directly from the [nginx-proxy documentation](https://github.com/jwilder/nginx-proxy#usage)... any container that you want available at a `*.docker` hostname via the proxy, you can set a `VIRTUAL_HOST` env var on, such as that example `docker run -e VIRTUAL_HOST=myapp.docker myapp`.

As a concrete example, you could run the official Grafana image and expose that container via the proxy with:

    docker run --rm -it -e VIRTUAL_HOST=grafana.docker grafana/grafana

And then it'd be available at http://grafana.docker

Please let me know if that makes sense and what I can do to clarify the documentation.

**Comment by jaesung2061** [comment]
Ok I got it.. I can try making a pull request to clarify a couple things. Would you like for me to try that?

**Comment by jaesung2061** [comment]
In my `docker-compose.yml` file, should all the services have the following?

```
environment:
    VIRTUAL_HOST=app.docker
```

I'm having issues connecting to my `mysql` service from my `app` service.

Update: I updated the mysql service to use `VIRTUAL_HOST=mysql.app.docker` and attempted to connect from host machine. It worked. But it doesn't work in the `app` container.

**Comment by jaesung2061** [comment]
Ok, I'm not sure what I did but I fixed the issue. It's super fast now btw (relatively), thanks for this package.
