### ISSUE TITLE
xdebug, port 9000

### ISSUE THREAD

**Issue by josefglatz** [codekitchen/dinghy-http-proxy#27]
Hi,

is it possible to also support xdebug with this proxy? I mostly use just xdebug without huge background knowledge.

Does it make sense?

**Comment by codekitchen** [comment]
I'm not familiar with xdebug, does it operate over HTTP?

**Comment by josefglatz** [comment]
Hi, thx for your answer. I tried to get more details on that topic. But I couldn't reproduce the behaviour on my second mac. Maybe it has something to do with OSX network stuff.. I don't know. So I would close it. And yes :-) > it's actually working as it should be.

Unfortunately, I can offer you no exact answer :-(
