### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by dimasch** [codekitchen/dinghy-http-proxy#3]
I'm get error on codekitchen/dinghy-http-proxy:2.0.3
https://i.imgur.com/bG5rWWm.png

https://i.imgur.com/EzlIPtr.png
`Dinghy 4.3.1`

```
2016/03/19 19:15:40 [error] 103#0: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.99.1, server: app.magento2.docker, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.17.0.5:443/favicon.ico", host: "app.magento2.docker", referrer: "http://app.magento2.docker/"
```

Thx,

**Comment by codekitchen** [comment]
This is touched on briefly in https://github.com/codekitchen/dinghy#http-proxy , but if your container exposes more than one port, the http proxy picks the first one it finds. To explicitly set which port to expose to the proxy, define a VIRTUAL_PORT env var for your container. In your case, it looks like the proxy chose port 443, but you probably want the forwarded port 80? I haven't tried it, but I don't think currently we'd successfully proxy a HTTPS backend.

**Comment by codekitchen** [comment]
I'm going to close this @dimasch as that should solve the problem. Let me know if it didn't.

**Comment by jscheel** [comment]
@codekitchen I've run into this, and I can't get it to work. I removed the second port that I added in my compose.yml, I've rebuilt my container, restarted dinghy, restarted the computer, nothing seems to work. I get nothing but the 502 error now. What am I doing wrong?
