### ISSUE TITLE
new cert and docker tag change broke old dinghy behaviour

### ISSUE THREAD

**Issue by paradite** [codekitchen/dinghy-http-proxy#40]
Hi, we encountered some issues with `dinghy-http-proxy`. Would be nice if you can take a look.
this commit https://github.com/codekitchen/dinghy-http-proxy/commit/d96dbee0b89eb208cbfa63735982c1b1ae470311
added check for `/etc/nginx/dhparam.pem` in `dinghy-http-proxy:2.5` docker image:
https://hub.docker.com/r/codekitchen/dinghy-http-proxy/tags/

however, the file in is not in dinghy machine, resulting in this error:
```
docker@dinghy:~$ docker exec 095 nginx -s reload
2017/10/24 06:51:48 [emerg] 77#77: BIO_new_file("/etc/nginx/dhparam.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/dhparam.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: [emerg] BIO_new_file("/etc/nginx/dhparam.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/dhparam.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)
docker@dinghy:~$ exit status 1
```

we can only bypass the error manually by executing
```
docker exec <conatiner_id> openssl dhparam -dsaparam -out /etc/nginx/dhparam.pem 4096
```
can you help to fix the issue so that `dinghy` creates the file automatically? or are we missing something very obvious?

**Comment by paradite** [comment]
update: it is generated, but appears to be in a different location:
according to https://github.com/jwilder/nginx-proxy/blob/02121df3b914061040df128e8266ccad81ce3046/generate-dhparam.sh#L9
```
/etc/nginx/dhparam/dhparam.pem
```

**Comment by codekitchen** [comment]
Hm shoot, I wonder why I didn't run into that in my testing. I will dig into this later today.

**Comment by codekitchen** [comment]
PR merged, this should be fixed as soon as the new build finishes here: https://hub.docker.com/r/codekitchen/dinghy-http-proxy/builds/

**Comment by paradite** [comment]
thanks so much for the fast response!
