### ISSUE TITLE
docker: Error response from daemon: unauthorized: incorrect username or password.

### ISSUE THREAD

**Issue by HardeepAsrani** [codekitchen/dinghy-http-proxy#47]
I get this issue when installing on my Mac. Same with friend. Have been using it for months without any issues before this setup:

`docker: Error response from daemon: Get https://registry-1.docker.io/v2/codekitchen/dinghy-http-proxy/manifests/latest: unauthorized: incorrect username or password.`

**Comment by codekitchen** [comment]
It sounds like you at one point logged into the docker registry, but your username/password combo that is cached in your Mac docker config files is currently invalid. Maybe a changed password? The docs for that: https://docs.docker.com/engine/reference/commandline/login/

Try doing a `docker pull` on some other public images from the registry, like `docker pull redis`, does that fail too?

**Comment by HardeepAsrani** [comment]
I'm able to pull other images easily. Will try to see if the password is cache when I get some time and let you know. I will close the ticket until then and will reopen if needed. Thanks for the instant reply, and sorry for being lazy. 😄
