### ISSUE TITLE
Automate DockerHub builds when jwilder/nginx-proxy updates

### ISSUE THREAD

**Issue by schliflo** [codekitchen/dinghy-http-proxy#53]
As jwilder/nginx-proxy is updated more frequently than this project, I'd suggest setting up automated builds for the base image in DockerHub:
<img width="687" alt="Screenshot 2020-06-25 at 21 13 02" src="https://user-images.githubusercontent.com/9881672/85784746-e3fffa00-b728-11ea-93da-fec1684f9c53.png">

**Comment by codekitchen** [comment]
Honestly I've avoided it precisely because I update this project so rarely, I worry that eventually an upstream change to nginx-proxy would break this build from working properly. This is just a local proxy used for development purposes so I'm not too concerned about staying completely up-to-date.

**Comment by codekitchen** [comment]
I'm going to close this as it's not something I plan to do. If anything I'd probably go the other direction and not base the image on jwilder/nginx-proxy anymore. It's diverged quite a lot, and at this point I'm probably introducing fragility more than really gaining anything.

**Comment by schliflo** [comment]
Fair enough. Thanks for clarifying. 👍
